
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package operacionesbasicasb;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int por = 7;
  public static final int para = 3;
  public static final int num = 2;
  public static final int error = 1;
  public static final int mas = 5;
  public static final int menos = 6;
  public static final int parc = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "para",
  "parc",
  "mas",
  "menos",
  "por"
  };
}

