
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package operacionesbasicasa;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int para = 6;
  public static final int por = 5;
  public static final int num = 2;
  public static final int error = 1;
  public static final int mas = 3;
  public static final int menos = 4;
  public static final int parc = 7;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "mas",
  "menos",
  "por",
  "para",
  "parc"
  };
}

